---
- name: Converge with logdy service disabled
  hosts: all
  gather_facts: true
  become: true
  pre_tasks:
    - name: Update cache(apt)
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts.pkg_mgr == 'apt'
      changed_when: false
    - name: Update cache(dnf)
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_facts.pkg_mgr == 'dnf'
      changed_when: false
  tasks:
    - name: Include role with autostart disabled
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        logdy_service_enabled: false
        logdy_service_state: stopped
