# code: language=ansible
---
- name: Create/update environment file
  ansible.builtin.template:
    src: environment_file.j2
    dest: /etc/default/logdy
    mode: "0644"
  notify: Restart logdy
- name: Create/update systemd unit file
  ansible.builtin.template:
    src: logdy.service.j2
    dest: /lib/systemd/system/logdy.service
    mode: "0644"
  notify: Restart logdy
  when: ansible_facts.service_mgr == 'systemd'
- name: Service logdy is active and enabled on system startup
  ansible.builtin.systemd_service:
    name: logdy
    state: "{{ logdy_service_state }}"
    enabled: "{{ logdy_service_enabled }}"
    daemon_reload: true
  when: ansible_facts.service_mgr == 'systemd'
- name: Allow logdy port
  community.general.ufw:
    rule: allow
    port: "{{  logdy_port }} "
    from_ip: "{{ logdy_allow_connect_other_host | default('any') }} "
  when: logdy_allow_connect_other_host is defined
